USE DiscoveryChallenge;

/*Are negative or positive reviews more helpful?*/

/*SELECT DISTINCT T1.RESTAURANT, T1.FIVECOUNT, T2.TOTALCOUNT, T1.FIVECOUNT/T2.TOTALCOUNT AS FIVE_STAR_RATIO
FROM (SELECT RESTAURANT, RANK, COUNT(TA1.REVIEW_STARS) AS FIVECOUNT
        FROM TRIPADVISOR TA1
        WHERE TA1.REVIEW_STARS= 5 GROUP BY RESTAURANT) T1 JOIN 
    (SELECT RESTAURANT, COUNT(TA2.REVIEW_STARS) AS TOTALCOUNT
        FROM TRIPADVISOR TA2
        GROUP BY RESTAURANT) T2 ON T1.RESTAURANT=T2.RESTAURANT
ORDER BY T1.RANK ASC;  */

SELECT USER_NAME, USER_HELPFUL_VOTES, USER_REVIEWS, USER_HELPFUL_VOTES/USER_REVIEWS AS HELPFULNESS_PER_REVIEW, AVG(REVIEW_STARS) AS AVG_REVIEW, COUNT(*)
FROM TRIPADVISOR
GROUP BY USER_NAME
ORDER BY HELPFULNESS_PER_REVIEW DESC; 