USE DiscoveryChallenge;

/*Are people meaner at a certain time of the year?*/

SELECT RESTAURANT, REVIEW_DATE, SUBSTRING_INDEX(REVIEW_DATE, '/', 1) AS MONTH, SUBSTRING(REVIEW_DATE, -4, 4) AS YEAR, AVG(REVIEW_STARS), COUNT(*) AS MONTH_TOTAL_REVIEW_COUNT, SUM(REVIEW_STARS)
FROM TRIPADVISOR
GROUP BY RESTAURANT, MONTH, YEAR
ORDER BY YEAR DESC;